#!/usr/bin/env bash

# vim mode (\q{keymap:vi/mode-indicator})
# set -o vi
# bleopt prompt_vi_mode_indicator=
# ble-bind -m vi_nmap -f 'C-c' 'vi-command/cancel'
# ble-bind -m vi_xmap -f 'C-c' 'vi-command/operator y'
# ble-bind -m vi_imap -f 'C-v' 'vi_nmap/paste-after'

# bleopt edit_bell=abell,vbell,visual
bleopt edit_abell=1
bleopt edit_vbell=1

bleopt vbell_default_message='arf, arf!'
bleopt vbell_duration=2000
bleopt vbell_align=right

ble-face vbell_flash='reverse,fg=green'

# bleopt color_scheme=base16
bleopt canvas_winch_action=redraw-here
bleopt complete_auto_complete=
bleopt prompt_command_changes_layout=1
bleopt history_share=1
bleopt info_display=bottom

ble/prompt/backslash:r_git() {
	ble/prompt/unit/add-hash '$PWD'
	if git rev-parse --is-inside-work-tree &> /dev/null; then
		branch=$(git rev-parse --abbrev-ref HEAD)

		remote=$(git remote get-url origin &>/dev/null)
		remote=${remote#*:}
		remote=${remote%%*.git}

		ble/prompt/print " (git:$branch${remote:+/$remote})"
	fi
}

ble/prompt/backslash:r_job() {
	ble/prompt/unit/add-hash '$PWD'
	ble/prompt/process-prompt-string " (job:\j)"
}

ble/prompt/backslash:fullpath() {
	ble/prompt/unit/add-hash '$PWD'
	ble/prompt/print "$PWD"
}

ble/prompt/backslash:userhash() {
	ble/prompt/unit/add-hash '$USER'

	case "$USER" in
	diamond) ble/prompt/print '$' ;;
	root)    ble/prompt/print '#' ;;
	*)       ble/prompt/print '?' ;;
	esac
}

ble/prompt/backslash:lineprompt_empty() {
	ble/prompt/unit/add-hash '$WIDTH'
	ble/prompt/print "$(lineprompt)"
}

PS1='\g{bold,fg=14}> \g{fg=14}\q{fullpath}\n\g{bold,fg=5}\q{userhash}\g{none} '
bleopt prompt_status_line='\h\r\q{r_job}\q{r_git} \q{position %d,%d}'
bleopt prompt_status_align=$'justify=\r'
bleopt prompt_ps1_transient=trim
bleopt prompt_ruler=$'\e[36m▁\e[0m'

ble-face prompt_status_line='fg=37'
