[global.channels]
 nixpkgs_unstable = "github:NixOS/nixpkgs nixos-unstable"
 nixpkgs_unstable_older = "github:NixOS/nixpkgs 7409480d5c"
 # nixpkgs_unstable_older = "github:NixOS/nixpkgs 1b1f50645af2a70dc93ea"
 nixpkgs_unstable_newer = "github:NixOS/nixpkgs 1c9db9710c"
 nixpkgs_gnome = "github:NixOS/nixpkgs 360bbbce42a" # gnome last Hydra
 home-manager_unstable = "github:nix-community/home-manager master"
 nixGL = "github:nix-community/nixGL main"

[global.aliases]
 nixos = "nixpkgs_unstable"
 nixpkgs = "nixpkgs_unstable"
 home-manager = "home-manager_unstable"

[flakes]
 enable = true

[users.root]
 use-sudo = true
 override-channels = true

[users.root.channels]
 # This specific commit contains kernel 6.1.9, which doesn't have the patch that
 # disables hi-res scrolling. We want this.
 nixpkgs_linux_6_1_9 = "github:NixOS/nixpkgs bafc851daff10fdda5eb6ed068234c46baeb4d0f"
 nixpkgs_21_11 = "github:NixOS/nixpkgs nixos-21.11"
 nixpkgs_staging = "github:NixOS/nixpkgs staging"
 nixpkgs_gradience = "github:foo-dogsquared/nixpkgs add-gradience-app"
 nixpkgs_shotcut = "github:MatthewCroughan/nixpkgs 6c3dbb326eeff83b11d7cb353c3cead30820e373"
 nix-wayland = "github:nix-community/nixpkgs-wayland master"
 lanzaboote = "github:nix-community/lanzaboote 45d04a45d3dfcdee5246f7c0dfed056313de2a61"
 prismlauncher = "github:PrismLauncher/PrismLauncher develop"
 mixxx2_4-beta = "github:mixxxdj/mixxx refs/tags/2.4-beta"
 gomod2nix = "github:nix-community/gomod2nix master"
 unstable = "https://nixos.org/channels/nixos-unstable"
 nur = "github:nix-community/NUR master"

[users.diamond]
 override-channels = false
