[root]
 use-sudo = true
 override-channels = true

[root.channels]
 # nixos = "github:NixOS/nixpkgs 1ffba9f"
 nixpkgs_21_11 = "github:NixOS/nixpkgs nixos-21.11"
 nixpkgs_unstable = "github:NixOS/nixpkgs nixos-unstable"
 nixpkgs_puffnfresh = "github:puffnfresh/nixpkgs pkgs/obs-backgroundremoval"
 nix-wayland = "github:nix-community/nixpkgs-wayland master"
 home-manager_21_11 = "github:nix-community/home-manager release-21.11"
 home-manager_unstable = "github:nix-community/home-manager 742c6cb"
 polymc = "github:PolyMC/PolyMC develop"
 unstable = "https://nixos.org/channels/nixos-unstable"

# TODO
[root.aliases]
 nixos = "nixpkgs_unstable"
 home-manager = "home-manager_unstable"

[diamond.channels]
 nixos = "github:NixOS/nixpkgs nixos-unstable"
 unstable = "https://nixos.org/channels/nixos-unstable"
