[root]
 use-sudo = true
 override-channels = true

[root.channels]
 nixos = "github:NixOS/nixpkgs 1ffba9f"
 nixpkgs21_11 = "github:NixOS/nixpkgs 8b3398bc7587ebb79f93dfeea1b8c574d3c6dba1"
 nix-wayland = "github:nix-community/nixpkgs-wayland master"
 home-manager = "github:nix-community/home-manager 742c6cb"
 polymc = "github:PolyMC/PolyMC develop"
 unstable = "https://nixos.org/channels/nixos-unstable"
