[root]
 use-sudo = true
 override-channels = true

[root.channels]
 # nixos = "github:NixOS/nixpkgs 1ffba9f"
 nixpkgs_21_11 = "github:NixOS/nixpkgs nixos-21.11"
 nixpkgs_pipewire_0_3_57 = "github:NixOS/nixpkgs b7a6fde153d"
 nixpkgs_unstable = "github:NixOS/nixpkgs 26c6895e1005b3e4f6dfe0d16afbd1f12d0a054c"
 nixpkgs_unstable_newer = "github:NixOS/nixpkgs nixos-unstable"
 nixpkgs_staging = "github:NixOS/nixpkgs staging"
 nixpkgs_gradience = "github:foo-dogsquared/nixpkgs add-gradience-app"
 nix-wayland = "github:nix-community/nixpkgs-wayland master"
 home-manager_21_11 = "github:nix-community/home-manager release-22.11"
 home-manager_unstable = "github:nix-community/home-manager release-22.11"
 prismlauncher = "github:PrismLauncher/PrismLauncher master"
 unstable = "https://nixos.org/channels/nixos-unstable"
 nur = "github:nix-community/NUR master"

# TODO
[root.aliases]
 nixos = "nixpkgs_unstable"
 home-manager = "home-manager_unstable"

[diamond]
 override-channels = false

[diamond.channels]
 nixos2 = "github:NixOS/nixpkgs c97e777ff06"
