# Do not modify this file!	It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.	Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
	imports = [
		<nixpkgs/nixos/modules/installer/scan/not-detected.nix>
	];

	boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
	boot.kernelModules = [ "kvm-intel" ];
	boot.extraModulePackages = [ ];

	fileSystems."/" = {
		device = "/dev/disk/by-uuid/bc6d7c51-0f68-4270-bede-d824b5179482";
		fsType = "ext4";
	};

	fileSystems."/home" = {
		device = "/dev/disk/by-uuid/20521e43-1c9d-4072-9042-163da42d9f0e";
		fsType = "ext4";
	};

	fileSystems."/boot" = {
		device = "/dev/disk/by-uuid/399D-8087";
		fsType = "vfat";
	};

	swapDevices = [
		{
			device = "/dev/disk/by-uuid/3c73d0ab-689f-4748-9cf0-a3eadeccac59";
		}
	];

	hardware = {
		opengl.driSupport32Bit = true;
		cpu.intel.updateMicrocode = true;
	};

	nix.maxJobs = lib.mkDefault 6;
	powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
