[global.channels]
 nixpkgs_gnome = "github:NixOS/nixpkgs gnome"
 nixpkgs_staging = "github:NixOS/nixpkgs staging"
 nixpkgs_unstable = "github:NixOS/nixpkgs nixos-unstable"
 home-manager_unstable = "github:nix-community/home-manager master"

[global.aliases]
 nixos = "nixpkgs_unstable"
 nixpkgs = "nixpkgs_unstable"
 home-manager = "home-manager_unstable"

[flakes]
 enable = true

[users.root]
 use-sudo = true
 override-channels = false

[users.root.channels]
 nixpkgs_unstable_newer = "github:NixOS/nixpkgs nixos-unstable"
 # I'm so fucking tired of Rust shit not building with a newer rustc version.
 # This is here to appease Asahi Linux's Rust crap.
 nixpkgs_older_rust = "github:NixOS/nixpkgs 85f1ba3e51676"
 nixos-apple-silicon = "github:tpwrules/nixos-apple-silicon main"
 asahilinux = "github:asahilinux/linux refs/tags/asahi-6.5-*"
 nur = "github:nix-community/NUR master"
 gomod2nix = "github:nix-community/gomod2nix master"

[users.diamond]
 override-channels = false
