[global.channels]
 nixpkgs_gnome = "github:NixOS/nixpkgs gnome"
 nixpkgs_unstable = "github:NixOS/nixpkgs nixos-unstable"
 home-manager_unstable = "github:nix-community/home-manager master"

[global.aliases]
 nixos = "nixpkgs_unstable"
 nixpkgs = "nixpkgs_unstable"
 home-manager = "home-manager_unstable"

[flakes]
 enable = true

[users.root]
 use-sudo = true
 override-channels = false

[users.root.channels]
 nixpkgs_unstable_newer = "github:NixOS/nixpkgs nixos-unstable"
 nixos-apple-silicon = "github:tpwrules/nixos-apple-silicon main"
 nur = "github:nix-community/NUR master"
 gomod2nix = "github:nix-community/gomod2nix master"

[users.diamond]
 override-channels = false
